dist: trusty
sudo: required

language: node_js
node_js:
  - node
  - 6
  - 7

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - oracle-java8-installer
      - google-chrome-stable
  sonarqube:
    organization: "adlerosn-github"
    token: $SONAR_TOKEN

before_script:
    - mkdir www
    - npm install -g npm@latest
    - npm install -g karma
    - npm install -g cordova
    - npm install -g ionic
    - npm install
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ionic platform remove browser
    - ionic platform add browser

script:
  - ionic build browser --prod
  - ng test --watch=false --code-coverage
  - sh -e /etc/init.d/xvfb stop
  - sonar-scanner

after_success:
    - ./node_modules/.bin/codecov -t $CODECOV_TOKEN

notifications:
  slack: econocart:HmGTsUw1lVIfPG29d8JGjP5c
